### ISSUE TITLE
Main content have to be centered

### ISSUE THREAD

**Issue by eko24ive** [vickyantre/Hw4#1]
![image](https://cloud.githubusercontent.com/assets/25591824/22870367/457a4dbe-f1af-11e6-961f-d08cffc9ef3d.png)

Use design reference:
![image](http://i.imgur.com/3hnKQeb.png)

**Comment by vickyantre** [comment]
Again I am not assured that I understand correctly, but i tried to fix.

**Comment by eko24ive** [comment]
You've did it right !
