### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by eko24ive** [vickyantre/Hw4#2]
Your navigation have some differences from design.
![image](https://cloud.githubusercontent.com/assets/25591824/22870381/665cc700-f1af-11e6-8d1a-6dde954de7c2.png)

Please, fix following things:
 - increase size of navigation
 - add border radius for the first and last navigation items
 - add padding for navigation items

Feel free to use design reference:
![image](https://cloud.githubusercontent.com/assets/25591824/22870399/9bb4a2ba-f1af-11e6-80bd-eb7b3b54e663.png)

**Comment by vickyantre** [comment]
fixed

**Comment by eko24ive** [comment]
Good job
